# Generated by Django 5.0.1 on 2024-01-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnioCarrera',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre_anio', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'anio_carrera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo_asignatura', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre_asignatura', models.CharField(blank=True, max_length=150, null=True)),
                ('descripccion', models.CharField(blank=True, max_length=255, null=True)),
                ('horas_practicas', models.SmallIntegerField(blank=True, null=True)),
                ('horas_teoricas', models.SmallIntegerField(blank=True, null=True)),
                ('total_horas', models.SmallIntegerField(blank=True, null=True)),
                ('pre_requisito1', models.CharField(blank=True, max_length=100, null=True)),
                ('pre_requisito2', models.CharField(blank=True, max_length=100, null=True)),
                ('anio_asignado', models.CharField(blank=True, db_comment='el a├▒o al que pertenece la materia', max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'asignatura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsignaturaCursada',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('anio_cursado', models.CharField(blank=True, max_length=20, null=True)),
                ('gestion_actual', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(blank=True, db_comment='aprobado/repro/cursando/abandonado', max_length=30, null=True)),
                ('fecha_inscripcion', models.DateTimeField(blank=True, null=True)),
                ('estado_inscripcion', models.CharField(blank=True, db_comment='si/concluido', max_length=30, null=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'asignatura_cursada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo_carrera', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre_carrera', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_creacion', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(blank=True, max_length=30, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'carrera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidop', models.CharField(blank=True, db_column='apellidoP', max_length=50, null=True)),
                ('apellidom', models.CharField(blank=True, db_column='apellidoM', max_length=50, null=True)),
                ('ci', models.SmallIntegerField(blank=True, null=True)),
                ('celular', models.SmallIntegerField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('profesion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=30, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'docente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentacionEstudiante',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('carta_postulacion', models.CharField(blank=True, max_length=10, null=True)),
                ('fot_diploma', models.CharField(blank=True, max_length=10, null=True)),
                ('fot_ci', models.CharField(blank=True, max_length=10, null=True)),
                ('fot_certificado_nacimiento', models.CharField(blank=True, max_length=10, null=True)),
                ('fotografia', models.CharField(blank=True, max_length=10, null=True)),
                ('fot_apoderados', models.CharField(blank=True, max_length=10, null=True)),
                ('carta_auspicio', models.CharField(blank=True, max_length=10, null=True)),
                ('certificacion_orga', models.CharField(blank=True, max_length=10, null=True)),
                ('carta_compromiso', models.CharField(blank=True, max_length=10, null=True)),
                ('formulario_ministerio', models.CharField(blank=True, max_length=10, null=True)),
                ('libreta_servicio_militar', models.CharField(blank=True, max_length=10, null=True)),
                ('boleta_pago', models.CharField(blank=True, max_length=10, null=True)),
                ('observacion', models.CharField(blank=True, max_length=10, null=True)),
                ('no_pertenece_unibol', models.CharField(blank=True, max_length=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'documentacion_estudiante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EducacionPrimaria',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('unidad_educativa', models.CharField(blank=True, max_length=100, null=True)),
                ('anio_egreso', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_colegio', models.CharField(blank=True, max_length=100, null=True)),
                ('pais_academico', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=50, null=True)),
                ('provincia', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'educacion_primaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('ci_estudiante', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('extencion', models.CharField(blank=True, max_length=20, null=True)),
                ('nombres', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidop', models.CharField(blank=True, db_column='apellidoP', max_length=50, null=True)),
                ('apellidom', models.CharField(blank=True, db_column='apellidoM', max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('celular', models.SmallIntegerField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('depa_nacimiento', models.CharField(blank=True, max_length=50, null=True)),
                ('fotografia', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=50, null=True)),
                ('idioma_nativo', models.CharField(blank=True, max_length=50, null=True)),
                ('idioma_regular', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion_estado', models.CharField(blank=True, max_length=255, null=True)),
                ('baja', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'estudiante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IdiomaOriginario',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre_idioma', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'idioma_originario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MallaAcademica',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('anio_aprobacion', models.CharField(blank=True, max_length=10, null=True)),
                ('doc_resolucion', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'malla_academica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre_municipio', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'municipio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotaEstudiante',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nota_num_normal', models.SmallIntegerField(blank=True, null=True)),
                ('instancia', models.CharField(blank=True, db_comment='si/no', max_length=20, null=True)),
                ('nota_num_instancia', models.SmallIntegerField(blank=True, null=True)),
                ('nota_num_final', models.SmallIntegerField(blank=True, null=True)),
                ('nota_literal_espaniol', models.CharField(blank=True, max_length=100, null=True)),
                ('nota_literal_quechua', models.CharField(blank=True, max_length=100, null=True)),
                ('gestion', models.CharField(blank=True, max_length=20, null=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'nota_estudiante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NumerosLetras',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('numeral', models.SmallIntegerField(blank=True, null=True)),
                ('literal_espaniol', models.CharField(blank=True, max_length=100, null=True)),
                ('literal_quechua', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'numeros_letras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('organizacion_matriz', models.CharField(blank=True, max_length=100, null=True)),
                ('organizacion_departamental', models.CharField(blank=True, max_length=100, null=True)),
                ('organizacion_regional', models.CharField(blank=True, max_length=100, null=True)),
                ('comunidad_sindicato', models.CharField(blank=True, max_length=100, null=True)),
                ('otros', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'organizacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre_provincia', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'provincia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResponsableEstudiante',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidop', models.CharField(blank=True, db_column='apellidoP', max_length=100, null=True)),
                ('apellidom', models.CharField(blank=True, db_column='apellidoM', max_length=100, null=True)),
                ('ci', models.SmallIntegerField(blank=True, null=True)),
                ('celular', models.SmallIntegerField(blank=True, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=255, null=True)),
                ('idioma', models.CharField(blank=True, max_length=50, null=True)),
                ('relacion_responsable', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'responsable_estudiante',
                'managed': False,
            },
        ),
    ]
